### PR TITLE
Second Beta revision of russian language

### PR DESCRIPTION
**Pull request by LHPixel**
Second Beta revision.

### CODE REVIEW

**Comment by LHPixel** [comment]
I can do an Ukrainian language.

**Comment by xsellier** [comment]
@LHPixel If you want to do Ukrainian I can create the yaml file, then you'll just have to pull the latest changes.

**Comment by LHPixel** [comment]
> @LHPixel If you want to do Ukrainian I can create the yaml file, then you'll just have to pull the latest changes.

Ok

**Comment by xsellier** [comment]
@LHPixel Please pull latest changes from this repository then you will see the uk.yml file.

**Pull request merged**
