### PR TITLE
I'd like to suggest a more "natural" description in spanish

### PR DESCRIPTION
**Pull request by Destroyerrrocket**
Hey! I'm interested in this game (I cannot buy it yet, I need a little bit of time). I was reading the description and I felt like it could be changed since right now it felt a little like it was auto-translated.

My suggestion is to use a closer style to the user with less formal words. For instance, the current translation uses the "usted" which does not suit this situation.

I've translated the first two paragraphs to give you an idea of what I'd do :)

### CODE REVIEW

**Comment by xsellier** [comment]
Spanish translation has been made by a friend. He is a native Spanish speaker, Im not sure that the description has a translation issue.

**Comment by xsellier** [comment]
I do understand, less formal way. Usted is too formal for a game. I get it!

**Comment by Destroyerrrocket** [comment]
> Spanish translation has been made by a friend. He is a native Spanish speaker, Im not sure that the description has a translation issue.

I'm not saying at all that it is an issue, it's just a suggestion :)
> I do understand, less formal way. Usted is too formal for a game. I get it!

Yeah, this extends to, for instance, words like "sus" and so. If you're okay with it, I'll also make these adjustments to the rest of the text.

**Comment by xsellier** [comment]
I'm open to suggestions, so if you want to continue the translation, I will take it.

**Pull request closed without merging**
