### PR TITLE
Modifications to the Spanish: BETA

### PR DESCRIPTION
**Pull request by xsellier**
We have fixed and corrected several lines of words.
As for example errors of the plural and singular, genres of game and very sophisticated words of the Spanish.
There are special cases where there are very English words and do not have an exact translation to Spanish, therefore we leave them in an original lenguage.
We will continue reviewing words, so it is not the end result but we move forward enough.

### CODE REVIEW

**Comment by Balthoraz** [comment]
Why this update? Is a complete step back of the actual branch updated. That ES file do not match with the one updated by me (0.25.3). Is a complete non-sense.

Binogure, with this update you completely rolled-back my update to a older version.

**Comment by xsellier** [comment]
Im sorry, Im gonna revert that change!

**Comment by xsellier** [comment]
This merge has been reverted. Sorry @Balthoraz I thought it was a good idea to merge those changes.
Im sorry. For the next es pull request Im gonna ping you if it is ok for you?

**Comment by Balthoraz** [comment]
Sure, no problem. I do not know where they got that file that translate "back" as "espalda" or Bankrupcy as "escrupulosidad bancaria". I never had those in the translation, and of course, is not from the actual branch.

**Pull request merged**
