### PR TITLE
Add Chinese

### PR DESCRIPTION
**Pull request by SteveThreenoon**
add chinese

### CODE REVIEW

**Comment by xsellier** [comment]
I already done it locally. Thank you for your help.

**Comment by xsellier** [comment]
I'm publishing a new version atm, on the unstable Steam branch, it should be available within 5 minutes. It'd be great if you can try it out (From Steam: right click on City Game Studio, select properties then Betas tab and select unstable)

**Comment by SteveThreenoon** [comment]
I've received that and I'll try it right now.  ;-)
Btw I think that the font of Chinese characters could be changed, because the font right now is too out of fashioned. I have some choices that are high quality and free to use for business, what's your opinion?

**Comment by xsellier** [comment]
May you share some of them please, I'm gonna try them out!

**Comment by SteveThreenoon** [comment]
Of course. Could you please give me your Dropbox email or the tool you use to transfer files? What we use in China maybe a little bit slow in where you guys in :-(

**Comment by xsellier** [comment]
Can you use this website?
https://drop.chapril.org/

**Comment by SteveThreenoon** [comment]
Yeah, I did that. [https://drop.chapril.org/download/6bc9f2a67af27852/#h0DFAYazuc6DV1G-BTTTpA](url)
Some of the files in those folders are Chinese .txt or .doc files, you could just ignore those and install them directly. I'm very sure that those fonts are free to use for business.

**Comment by xsellier** [comment]
I used this font: SourceHanSansCN
More readable and better rendering.

Thank you

**Pull request closed without merging**
